version: "3.9"
services:
  web:
    image: ghcr.io/distwi/distwi-client:latest
    container_name: dtwin_web
    restart: unless-stopped
    depends_on: [api]
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    pull_policy: always

  api:
    image: ghcr.io/distwi/distwi-server:latest
    container_name: dtwin_api
    restart: unless-stopped
    env_file:
      - .env         # this file must be next to compose.prod.yml on the server
    pull_policy: always
