name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name of Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push client image
      uses: docker/build-push-action@v3
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/distwi-client:latest

    - name: Build and push server image
      uses: docker/build-push-action@v3
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/distwi-server:latest